### ISSUE TITLE
Deprecation warning in Ember 3.5

### ISSUE THREAD

**Issue by patrickberkeley** [bustle/ember-mobiledoc-editor#160]
In Ember 3.5.1 we are seeing a warning:

```
deprecate.js:102 DEPRECATION: You called <bnb@component:mobiledoc-editor::ember5870>.sendAction("did-create-editor") but Component#sendAction is deprecated. Please use closure actions instead. [deprecation id: ember-component.send-action] See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.
```

Is this a known issue?

**Comment by backspace** [comment]
It’s an issue in a lot of addons but won’t be a real problem until Ember 4.0, according to [the documentation](https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-component-send-action). However, I’ve submitted a PR to fix it regardless; it may need some guidance from the maintainers but it’s a start!
