### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by amk221** [bustle/ember-mobiledoc-editor#189]
I'm looking at using this ember addon, but noticed that when installing this error is output:

```
You cannot access this.$() with `jQuery` disabled
```

(Seeing as though `"jquery-integration": false` is the default now)

I can see this was fixed, but not release yet. Is there a timeframe for the next version?

Thanks!

**Comment by cloke** [comment]
@lukemelia just bumping this. Is there any possibility of getting this into the release. Our fallback plan is to just point to a fork in our organization, but we'd love to help push this forward after the jQuery removal goes live.

**Comment by lukemelia** [comment]
Release as v0.7.0. Sorry it took so long!
